name: Deploy to Cloud Run

on:
  push:
    branches:
      - main
      - gcp-dev

env:
  CICD_PROJECT_ID: 'prj-cicd-solarad'
  DEPLOY_PROJECT_ID: 'prj-prod-solarad-7a'
  REGION: 'asia-south2'
  ARTIFACT_REPO: 'asia-south2-docker.pkg.dev/prj-cicd-solarad/repo-solarad-cicd-as2-01'
  SERVICE_NAME: 'credocarbon-website-backend'

jobs:
  # Build and deploy API
  deploy-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Auth for CI/CD (build and push)
      - name: Auth for CI/CD
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ env.CICD_PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_CICD_AUTH }}

      - name: Set Environment Variables
        run: |
          echo "GIT_COMMIT_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "BUILD_ID=${{ github.run_number }}" >> $GITHUB_ENV

      - name: Configure Docker
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Build API Docker image
        run: |
          docker build -f Dockerfile \
            -t ${{ env.ARTIFACT_REPO }}/prod/${{ env.SERVICE_NAME }}:prod-${{ env.BUILD_ID }} \
            -t ${{ env.ARTIFACT_REPO }}/prod/${{ env.SERVICE_NAME }}:${{ env.GIT_COMMIT_SHORT }} \
            -t ${{ env.ARTIFACT_REPO }}/prod/${{ env.SERVICE_NAME }}:latest .

      - name: Push API image
        run: |
          docker push ${{ env.ARTIFACT_REPO }}/prod/${{ env.SERVICE_NAME }}:prod-${{ env.BUILD_ID }}
          docker push ${{ env.ARTIFACT_REPO }}/prod/${{ env.SERVICE_NAME }}:${{ env.GIT_COMMIT_SHORT }}
          docker push ${{ env.ARTIFACT_REPO }}/prod/${{ env.SERVICE_NAME }}:latest

      # Auth for PROD (deploy)
      - name: Auth for Deployment
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ env.DEPLOY_PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_PROD_AUTH }}

      - name: Deploy API to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --project ${{ env.DEPLOY_PROJECT_ID }} \
            --image ${{ env.ARTIFACT_REPO }}/prod/${{ env.SERVICE_NAME }}:latest \
            --platform managed \
            --region ${{ env.REGION }} \
            --allow-unauthenticated \
            --port 8080 \
            --update-env-vars SECRET_KEY="${{ secrets.SECRET_KEY }}" \
            --update-env-vars CORS_ORIGINS="${{ secrets.CORS_ORIGINS }}" \
            --update-env-vars ADMIN_USERNAME="${{ secrets.ADMIN_USERNAME }}" \
            --update-env-vars ADMIN_PASSWORD="${{ secrets.ADMIN_PASSWORD }}" \
            --update-env-vars USE_GCS="true" \
            --update-env-vars GCS_BUCKET_NAME="credocarbon-metadata"

